# -*- coding: utf-8 -*-
"""
S&P 500 公司名/别名 → 美股代码映射（供 build_graph 中 _canonicalize_ticker 使用）
来源：Wikipedia List of S&P 500 companies + 常见财经新闻写法
"""

# 全量映射：key 为 UPPER 后的公司名或别名，value 为 ticker（与图节点一致，如 BRK.B）
NAME_TO_TICKER = {
    # 信息技术
    "APPLE": "AAPL", "APPLE INC": "AAPL", "APPLE INC.": "AAPL", "APPLE INCORPORATED": "AAPL",
    "MICROSOFT": "MSFT", "MICROSOFT CORP": "MSFT", "MICROSOFT CORPORATION": "MSFT",
    "NVIDIA": "NVDA", "NVIDIA CORP": "NVDA", "NVIDIA CORPORATION": "NVDA",
    "BROADCOM": "AVGO", "AVAGO": "AVGO",
    "CISCO": "CSCO", "CISCO SYSTEMS": "CSCO",
    "ADOBE": "ADBE", "ADOBE INC": "ADBE", "ADOBE SYSTEMS": "ADBE",
    "SALESFORCE": "CRM", "SALESFORCE.COM": "CRM",
    "ORACLE": "ORCL", "ORACLE CORP": "ORCL",
    "ACCENTURE": "ACN", "IBM": "IBM", "INTERNATIONAL BUSINESS MACHINES": "IBM",
    "INTEL": "INTC", "INTEL CORP": "INTC",
    "AMD": "AMD", "ADVANCED MICRO DEVICES": "AMD",
    "QUALCOMM": "QCOM", "TEXAS INSTRUMENTS": "TXN", "TI": "TXN",
    "APPLIED MATERIALS": "AMAT", "AMAT": "AMAT",
    "MICRON": "MU", "MICRON TECHNOLOGY": "MU",
    "LAM RESEARCH": "LRCX", "LRCX": "LRCX",
    "ANALOG DEVICES": "ADI", "ADI": "ADI",
    "KLA": "KLAC", "KLA CORP": "KLAC", "KLA TENCOR": "KLAC",
    "SYNOPSYS": "SNPS", "CADENCE": "CDNS", "CDNS": "CDNS",
    "MICROCHIP": "MCHP", "MICROCHIP TECHNOLOGY": "MCHP",
    "NXP": "NXPI", "NXP SEMICONDUCTORS": "NXPI",
    "MONOLITHIC POWER": "MPWR", "MPWR": "MPWR",
    "FORTINET": "FTNT", "PALO ALTO": "PANW", "PALO ALTO NETWORKS": "PANW",
    "SERVICENOW": "NOW", "SERVICE NOW": "NOW",
    "INTUIT": "INTU", "AUTODESK": "ADSK", "ADSK": "ADSK",
    "ANSYS": "ANSS", "PAYPAL": "PYPL", "FIS": "FIS", "FIDELITY NATIONAL": "FIS",
    "FISERV": "FISV", "GLOBAL PAYMENTS": "GPN", "GPN": "GPN",
    "ADP": "ADP", "AUTOMATIC DATA PROCESSING": "ADP",
    "PAYCHEX": "PAYX", "COGNIZANT": "CTSH", "GARTNER": "IT", "IT": "IT",
    "EPAM": "EPAM", "AKAMAI": "AKAM", "AKAMAI TECHNOLOGIES": "AKAM",
    # 医疗保健
    "UNITEDHEALTH": "UNH", "UNITED HEALTH": "UNH", "UNITEDHEALTH GROUP": "UNH",
    "JOHNSON & JOHNSON": "JNJ", "JOHNSON AND JOHNSON": "JNJ", "JNJ": "JNJ",
    "ELI LILLY": "LLY", "LILLY": "LLY", "LLY": "LLY",
    "PFIZER": "PFE", "PFE": "PFE",
    "ABBVIE": "ABBV", "ABBV": "ABBV",
    "MERCK": "MRK", "MERCK & CO": "MRK", "MRK": "MRK",
    "THERMO FISHER": "TMO", "THERMO FISHER SCIENTIFIC": "TMO", "TMO": "TMO",
    "ABBOTT": "ABT", "ABBOTT LABORATORIES": "ABT", "ABT": "ABT",
    "DANAHER": "DHR", "DHR": "DHR",
    "BRISTOL MYERS": "BMY", "BRISTOL-MYERS SQUIBB": "BMY", "BMY": "BMY",
    "AMGEN": "AMGN", "GILEAD": "GILD", "GILEAD SCIENCES": "GILD",
    "VERTEX": "VRTX", "VERTEX PHARMACEUTICALS": "VRTX", "REGN": "REGN", "REGENERON": "REGN",
    "INTUITIVE SURGICAL": "ISRG", "ISRG": "ISRG",
    "MEDTRONIC": "MDT", "MDT": "MDT",
    "STRYKER": "SYK", "SYK": "SYK",
    "BECTON DICKINSON": "BDX", "BD": "BDX", "BDX": "BDX",
    "BOSTON SCIENTIFIC": "BSX", "BSX": "BSX",
    "EDWARDS LIFESCIENCES": "EW", "EW": "EW",
    "ZIMMER BIOMET": "ZBH", "ZBH": "ZBH",
    "IDEXX": "IDXX", "IDXX LABORATORIES": "IDXX",
    "DEXCOM": "DXCM", "ALIGN": "ALGN", "ALIGN TECHNOLOGY": "ALGN",
    "HOLOGIC": "HOLX", "METTLER TOLEDO": "MTD", "IQVIA": "IQV",
    "CIGNA": "CI", "CIGNA CORP": "CI", "ELEVANCE": "ELV", "ELEVANCE HEALTH": "ELV",
    "HUMANA": "HUM", "CVS": "CVS", "CVS HEALTH": "CVS",
    "MCKESSON": "MCK", "CARDINAL HEALTH": "CAH", "CAH": "CAH",
    "AMERISOURCEBERGEN": "ABC", "ABC": "ABC",
    "CENTENE": "CNC", "MOLINA": "MOH", "HCA": "HCA", "HCA HEALTHCARE": "HCA",
    "UNIVERSAL HEALTH": "UHS", "UHS": "UHS", "DAVITA": "DVA",
    "LABCORP": "LH", "LABORATORY CORP": "LH",
    "QUEST DIAGNOSTICS": "DGX", "DGX": "DGX",
    "AGILENT": "A", "WATERS": "WAT", "PERKINELMER": "PKI",
    "BIO-RAD": "BIO", "HENRY SCHEIN": "HSIC", "COOPER": "COO", "COOPER COMPANIES": "COO",
    "RESMED": "RMD", "BAXTER": "BAX", "BAX": "BAX",
    # 金融
    "BERKSHIRE HATHAWAY": "BRK.B", "BERKSHIRE": "BRK.B", "BRK.B": "BRK.B", "BRK B": "BRK.B",
    "JPMORGAN": "JPM", "JPMORGAN CHASE": "JPM", "JP MORGAN": "JPM", "CHASE": "JPM",
    "VISA": "V", "V": "V",
    "MASTERCARD": "MA", "MA": "MA",
    "BANK OF AMERICA": "BAC", "BAC": "BAC",
    "WELLS FARGO": "WFC", "WFC": "WFC",
    "GOLDMAN SACHS": "GS", "GS": "GS",
    "MORGAN STANLEY": "MS", "MS": "MS",
    "CHARLES SCHWAB": "SCHW", "SCHWAB": "SCHW",
    "AMERICAN EXPRESS": "AXP", "AMEX": "AXP", "AXP": "AXP",
    "BLACKROCK": "BLK", "BLK": "BLK",
    "S&P GLOBAL": "SPGI", "SP GLOBAL": "SPGI", "MCGRAW HILL": "SPGI",
    "CITIGROUP": "C", "CITI": "C", "C": "C",
    "PNC": "PNC", "PNC FINANCIAL": "PNC",
    "US BANCORP": "USB", "U.S. BANCORP": "USB", "USB": "USB",
    "TRUIST": "TFC", "TFC": "TFC",
    "CME GROUP": "CME", "CME": "CME",
    "INTERCONTINENTAL EXCHANGE": "ICE", "ICE": "ICE",
    "CHUBB": "CB", "CB": "CB",
    "MARSH MCLENNAN": "MMC", "MMC": "MMC",
    "AON": "AON", "PROGRESSIVE": "PGR", "PGR": "PGR",
    "AIG": "AIG", "AMERICAN INTERNATIONAL GROUP": "AIG",
    "METLIFE": "MET", "MET": "MET",
    "PRUDENTIAL": "PRU", "PRU": "PRU",
    "AFLAC": "AFL", "AFL": "AFL",
    "ALLSTATE": "ALL", "ALL": "ALL",
    "TRAVELERS": "TRV", "TRV": "TRV",
    "CINCINNATI FINANCIAL": "CINF", "CINF": "CINF",
    "HARTFORD": "HIG", "THE HARTFORD": "HIG",
    "ARTHUR J GALLAGHER": "AJG", "GALLAGHER": "AJG",
    "WILLIS TOWERS WATSON": "WTW", "WTW": "WTW",
    "BROWN & BROWN": "BRO", "BRO": "BRO",
    "EVEREST RE": "RE", "RE": "RE",
    "LOEWS": "L", "L": "L",
    "GLOBUS MEDICAL": "GL", "GL": "GL",
    "CAPITAL ONE": "COF", "COF": "COF",
    "DISCOVER": "DFS", "DISCOVER FINANCIAL": "DFS",
    "SYNCHRONY": "SYF", "ALLY": "ALLY", "ALLY FINANCIAL": "ALLY",
    "M&T BANK": "MTB", "MTB": "MTB",
    "FIFTH THIRD": "FITB", "FITB": "FITB",
    "HUNTINGTON": "HBAN", "HBAN": "HBAN",
    "KEYBANC": "KEY", "KEY BANK": "KEY", "KEYBANC CAPITAL": "KEY", "KEY": "KEY",
    "REGIONS": "RF", "REGIONS FINANCIAL": "RF",
    "CITIZENS": "CFG", "CITIZENS FINANCIAL": "CFG",
    "ZIONS": "ZION", "ZIONS BANCORP": "ZION",
    "NORTHERN TRUST": "NTRS", "NTRS": "NTRS",
    "STATE STREET": "STT", "STT": "STT",
    "BANK OF NEW YORK": "BK", "BNY MELLON": "BK", "BK": "BK",
    # 通信服务
    "GOOGLE": "GOOGL", "ALPHABET": "GOOGL", "GOOGLE INC": "GOOGL", "GOOGL": "GOOGL", "GOOG": "GOOGL",
    "META": "META", "FACEBOOK": "META", "META PLATFORMS": "META",
    "NETFLIX": "NFLX", "NFLX": "NFLX",
    "DISNEY": "DIS", "WALT DISNEY": "DIS", "WALT DISNEY COMPANY": "DIS", "DIS": "DIS",
    "COMCAST": "CMCSA", "CMCSA": "CMCSA",
    "VERIZON": "VZ", "VZ": "VZ",
    "AT&T": "T", "ATT": "T", "T": "T",
    "T-MOBILE": "TMUS", "TMUS": "TMUS", "SPRINT": "TMUS",
    "CHARTER": "CHTR", "CHARTER COMMUNICATIONS": "CHTR",
    "ACTIVISION": "ATVI", "ACTIVISION BLIZZARD": "ATVI",
    "ELECTRONIC ARTS": "EA", "EA": "EA",
    "TAKE-TWO": "TTWO", "TAKE TWO": "TTWO", "TTWO": "TTWO",
    "WARNER BROS DISCOVERY": "WBD", "WARNER MEDIA": "WBD", "WBD": "WBD",
    "PARAMOUNT": "PARA", "PARA": "PARA",
    "FOX": "FOX", "FOX CORP": "FOX", "FOXA": "FOXA",
    "NEWS CORP": "NWS", "NWS": "NWS", "NWSA": "NWSA",
    "OMNICOM": "OMC", "OMC": "OMC",
    "INTERPUBLIC": "IPG", "IPG": "IPG",
    "LIVE NATION": "LYV", "LYV": "LYV",
    "MATCH": "MTCH", "MATCH GROUP": "MTCH",
    "ZILLOW": "ZG", "ZG": "ZG",
    "PINTEREST": "PINS", "PINS": "PINS",
    # 可选消费
    "AMAZON": "AMZN", "AMAZON.COM": "AMZN", "AMAZON COM": "AMZN", "AMZN": "AMZN",
    "TESLA": "TSLA", "TESLA MOTORS": "TSLA", "TESLA INC": "TSLA", "TSLA": "TSLA",
    "HOME DEPOT": "HD", "HD": "HD",
    "MCDONALD'S": "MCD", "MCDONALDS": "MCD", "MCDONALD": "MCD", "MCD": "MCD",
    "NIKE": "NKE", "NKE": "NKE",
    "LOWE'S": "LOW", "LOWES": "LOW", "LOW": "LOW",
    "STARBUCKS": "SBUX", "SBUX": "SBUX",
    "TJX": "TJX", "TJ MAXX": "TJX",
    "BOOKING": "BKNG", "BOOKING HOLDINGS": "BKNG", "PRICELINE": "BKNG",
    "MARRIOTT": "MAR", "MARRIOTT INTERNATIONAL": "MAR",
    "HILTON": "HLT", "HLT": "HLT",
    "CHIPOTLE": "CMG", "CMG": "CMG",
    "O'REILLY": "ORLY", "OREILLY": "ORLY", "ORLY": "ORLY",
    "AUTOZONE": "AZO", "AZO": "AZO",
    "ROSS": "ROST", "ROSS STORES": "ROST",
    "D.R. HORTON": "DHI", "DR HORTON": "DHI", "DHI": "DHI",
    "LENNAR": "LEN", "LEN": "LEN",
    "PULTE": "PHM", "PULTE HOMES": "PHM",
    "NVR": "NVR",
    "GENERAL MOTORS": "GM", "GM": "GM",
    "FORD": "F", "F": "F",
    "APTV": "APTV", "APTIV": "APTV",
    "BORG WARNER": "BWA", "BWA": "BWA",
    "LEAR": "LEA", "LEA": "LEA",
    "RALPH LAUREN": "RL", "RL": "RL",
    "TAPESTRY": "TPR", "COACH": "TPR",
    "VF CORP": "VFC", "VFC": "VFC",
    "PVH": "PVH", "CALVIN KLEIN": "PVH",
    "HASBRO": "HAS", "HAS": "HAS",
    "MATTEL": "MAT", "MAT": "MAT",
    "DARDEN": "DRI", "OLIVE GARDEN": "DRI",
    "YUM": "YUM", "YUM BRANDS": "YUM", "KFC": "YUM", "TACO BELL": "YUM", "PIZZA HUT": "YUM",
    "WYNN": "WYNN", "WYNN RESORTS": "WYNN",
    "MGM": "MGM", "MGM RESORTS": "MGM",
    "CAESARS": "CZR", "CZR": "CZR",
    "ROYAL CARIBBEAN": "RCL", "RCL": "RCL",
    "CARNIVAL": "CCL", "CCL": "CCL",
    "NORWEGIAN": "NCLH", "NCLH": "NCLH",
    "LAS VEGAS SANDS": "LVS", "LVS": "LVS",
    "EXPEDIA": "EXPE", "EXPE": "EXPE",
    "AIRBNB": "ABNB", "ABNB": "ABNB",
    "UBER": "UBER", "UBER TECHNOLOGIES": "UBER",
    "LYFT": "LYFT", "DOORDASH": "DASH", "DASH": "DASH",
    "EBAY": "EBAY", "ETSY": "ETSY",
    "WAYFAIR": "W", "W": "W",
    "BEST BUY": "BBY", "BBY": "BBY",
    "CARMAX": "KMX", "KMX": "KMX",
    "AUTONATION": "AN", "AN": "AN",
    # 必需消费
    "PROCTER & GAMBLE": "PG", "P&G": "PG", "PG": "PG",
    "COCA-COLA": "KO", "COCA COLA": "KO", "KO": "KO",
    "PEPSICO": "PEP", "PEPSI": "PEP", "PEP": "PEP",
    "COSTCO": "COST", "COSTCO WHOLESALE": "COST", "COST": "COST",
    "WALMART": "WMT", "WAL-MART": "WMT", "WMT": "WMT",
    "PHILIP MORRIS": "PM", "PM": "PM",
    "ALTRIA": "MO", "MO": "MO",
    "MONDELEZ": "MDLZ", "MDLZ": "MDLZ",
    "COLGATE": "CL", "COLGATE-PALMOLIVE": "CL", "CL": "CL",
    "ESTEE LAUDER": "EL", "EL": "EL",
    "KIMBERLY CLARK": "KMB", "KMB": "KMB",
    "GENERAL MILLS": "GIS", "GIS": "GIS",
    "KELLOGG": "K", "K": "K",
    "HERSHEY": "HSY", "HSY": "HSY",
    "HORMEL": "HRL", "HRL": "HRL",
    "JM SMUCKER": "SJM", "SMUCKER": "SJM",
    "MCCORMICK": "MKC", "MKC": "MKC",
    "CONAGRA": "CAG", "CAG": "CAG",
    "CAMPBELL": "CPB", "CAMPBELL SOUP": "CPB",
    "TYSON": "TSN", "TYSON FOODS": "TSN", "TSN": "TSN",
    "KRAFT HEINZ": "KHC", "KHC": "KHC",
    "CONSTELLATION": "STZ", "CONSTELLATION BRANDS": "STZ", "STZ": "STZ",
    "BROWN FORMAN": "BF.B", "BFB": "BF.B",
    "MOLSON COORS": "TAP", "TAP": "TAP",
    "KEURIG DR PEPPER": "KDP", "KDP": "KDP",
    "MONSTER": "MNST", "MONSTER BEVERAGE": "MNST", "MNST": "MNST",
    "WALGREENS": "WBA", "WALGREENS BOOTS": "WBA", "WBA": "WBA",
    "SYSCO": "SYY", "SYY": "SYY",
    "KROGER": "KR", "KR": "KR",
    "TARGET": "TGT", "TGT": "TGT",
    "DOLLAR GENERAL": "DG", "DG": "DG",
    "DOLLAR TREE": "DLTR", "DLTR": "DLTR",
    "CLOROX": "CLX", "CLX": "CLX",
    "CHURCH & DWIGHT": "CHD", "CHD": "CHD",
    "CORE-MARK": "COR", "COR": "COR",
    # 工业
    "UNION PACIFIC": "UNP", "UNP": "UNP",
    "UPS": "UPS", "UNITED PARCEL": "UPS",
    "HONEYWELL": "HON", "HON": "HON",
    "BOEING": "BA", "BA": "BA",
    "RTX": "RTX", "RAYTHEON": "RTX", "RAYTHEON TECHNOLOGIES": "RTX",
    "CATERPILLAR": "CAT", "CAT": "CAT",
    "JOHN DEERE": "DE", "DEERE": "DE", "DE": "DE",
    "LOCKHEED MARTIN": "LMT", "LOCKHEED": "LMT", "LMT": "LMT",
    "GENERAL ELECTRIC": "GE", "GE": "GE",
    "3M": "MMM", "MMM": "MMM",
    "GENERAL DYNAMICS": "GD", "GD": "GD",
    "NORTHROP GRUMMAN": "NOC", "NOC": "NOC",
    "L3HARRIS": "LHX", "LHX": "LHX",
    "TRANSDIGM": "TDG", "TDG": "TDG",
    "ILLINOIS TOOL": "ITW", "ITW": "ITW",
    "EMERSON": "EMR", "EMR": "EMR",
    "ROCKWELL": "ROK", "ROCKWELL AUTOMATION": "ROK",
    "PARKER HANNIFIN": "PH", "PH": "PH",
    "EATON": "ETN", "ETN": "ETN",
    "PACCAR": "PCAR", "PCAR": "PCAR",
    "CINTAS": "CTAS", "CTAS": "CTAS",
    "FASTENAL": "FAST", "FAST": "FAST",
    "WASTE MANAGEMENT": "WM", "WM": "WM",
    "REPUBLIC SERVICES": "RSG", "RSG": "RSG",
    "WASTE CONNECTIONS": "WCN", "WCN": "WCN",
    "VERISK": "VRSK", "VRSK": "VRSK",
    "COPART": "CPRT", "CPRT": "CPRT",
    "CSX": "CSX", "NORFOLK SOUTHERN": "NSC", "NSC": "NSC",
    "FEDEX": "FDX", "FDX": "FDX",
    "EXPEDITOR": "EXPD", "EXPD": "EXPD",
    "C.H. ROBINSON": "CHRW", "CH ROBINSON": "CHRW", "CHRW": "CHRW",
    "J.B. HUNT": "JBHT", "JB HUNT": "JBHT", "JBHT": "JBHT",
    "DELTA": "DAL", "DELTA AIR LINES": "DAL", "DAL": "DAL",
    "UNITED AIRLINES": "UAL", "UNITED": "UAL", "UAL": "UAL",
    "SOUTHWEST": "LUV", "SOUTHWEST AIRLINES": "LUV", "LUV": "LUV",
    "AMERICAN AIRLINES": "AAL", "AMERICAN": "AAL", "AAL": "AAL",
    "ALASKA AIR": "ALK", "ALK": "ALK",
    "CARRIER": "CARR", "CARR": "CARR",
    "OTIS": "OTIS", "OTIS WORLDWIDE": "OTIS",
    "JOHNSON CONTROLS": "JCI", "JCI": "JCI",
    "TRACTOR SUPPLY": "TT", "TT": "TT",
    "INGERSOLL RAND": "IR", "IR": "IR",
    "STANLEY BLACK DECKER": "SWK", "STANLEY": "SWK", "SWK": "SWK",
    "MASCO": "MAS", "MAS": "MAS",
    "GENERAC": "GNRC", "GNRC": "GNRC",
    "QUANTA": "PWR", "QUANTA SERVICES": "PWR", "PWR": "PWR",
    "AMETEK": "AME", "AME": "AME",
    "DOVER": "DOV", "DOV": "DOV",
    "ROPER": "ROP", "ROP": "ROP",
    # 能源
    "EXXON": "XOM", "EXXON MOBIL": "XOM", "EXXONMOBIL": "XOM", "XOM": "XOM",
    "CHEVRON": "CVX", "CVX": "CVX",
    "CONOCOPHILLIPS": "COP", "COP": "COP",
    "SCHLUMBERGER": "SLB", "SLB": "SLB",
    "EOG": "EOG", "EOG RESOURCES": "EOG",
    "MARATHON": "MPC", "MARATHON PETROLEUM": "MPC", "MPC": "MPC",
    "PHILLIPS 66": "PSX", "PSX": "PSX",
    "VALERO": "VLO", "VLO": "VLO",
    "PIONEER": "PXD", "PIONEER NATURAL": "PXD", "PXD": "PXD",
    "OCCIDENTAL": "OXY", "OXY": "OXY",
    "HESS": "HES", "HES": "HES",
    "DEVON": "DVN", "DEVON ENERGY": "DVN", "DVN": "DVN",
    "DIAMONDBACK": "FANG", "FANG": "FANG",
    "HALLIBURTON": "HAL", "HAL": "HAL",
    "BAKER HUGHES": "BKR", "BKR": "BKR",
    "KINDER MORGAN": "KMI", "KMI": "KMI",
    "WILLIAMS": "WMB", "WILLIAMS COMPANIES": "WMB", "WMB": "WMB",
    "ONEOK": "OKE", "OKE": "OKE",
    "TARGA": "TRGP", "TRGP": "TRGP",
    "APA": "APA", "APA CORP": "APA",
    "MARATHON OIL": "MRO", "MRO": "MRO",
    "COTERRA": "CTRA", "CTRA": "CTRA",
    # 材料
    "LINDE": "LIN", "LIN": "LIN",
    "AIR PRODUCTS": "APD", "APD": "APD",
    "SHERWIN-WILLIAMS": "SHW", "SHERWIN WILLIAMS": "SHW", "SHW": "SHW",
    "ECOLAB": "ECL", "ECL": "ECL",
    "DUPONT": "DD", "DUPONT DE NEMOURS": "DD", "DD": "DD",
    "DOW": "DOW", "DOW INC": "DOW",
    "NEWMONT": "NEM", "NEM": "NEM",
    "FREEPORT": "FCX", "FREEPORT MCMORAN": "FCX", "FCX": "FCX",
    "NUCOR": "NUE", "NUE": "NUE",
    "VULCAN": "VMC", "VMC": "VMC",
    "MARTIN MARIETTA": "MLM", "MLM": "MLM",
    "PPG": "PPG", "PPG INDUSTRIES": "PPG",
    "ALBEMARLE": "ALB", "ALB": "ALB",
    "EASTMAN": "EMN", "EASTMAN CHEMICAL": "EMN",
    "CELANESE": "CE", "CE": "CE",
    "CF INDUSTRIES": "CF", "CF": "CF",
    "MOSAIC": "MOS", "MOS": "MOS",
    "FMC": "FMC", "FMC CORP": "FMC",
    "IFF": "IFF", "INTERNATIONAL FLAVORS": "IFF",
    "CORTEVA": "CTVA", "CTVA": "CTVA",
    "LYONDELLBASELL": "LYB", "LYB": "LYB",
    "INTERNATIONAL PAPER": "IP", "IP": "IP",
    "PACKAGING CORP": "PKG", "PKG": "PKG",
    "SEALED AIR": "SEE", "SEE": "SEE",
    "AVERY DENNISON": "AVY", "AVY": "AVY",
    "BALL": "BALL", "BALL CORP": "BALL",
    "AMCOR": "AMCR", "AMCR": "AMCR",
    # 房地产
    "PROLOGIS": "PLD", "PLD": "PLD",
    "AMERICAN TOWER": "AMT", "AMT": "AMT",
    "CROWN CASTLE": "CCI", "CCI": "CCI",
    "EQUINIX": "EQIX", "EQIX": "EQIX",
    "PUBLIC STORAGE": "PSA", "PSA": "PSA",
    "SIMON": "SPG", "SIMON PROPERTY": "SPG", "SPG": "SPG",
    "REALTY INCOME": "O", "O": "O",
    "WELLTOWER": "WELL", "WELL": "WELL",
    "DIGITAL REALTY": "DLR", "DLR": "DLR",
    "AVALONBAY": "AVB", "AVB": "AVB",
    "EQUITY RESIDENTIAL": "EQR", "EQR": "EQR",
    "VENTAS": "VTR", "VTR": "VTR",
    "ALEXANDRIA": "ARE", "ARE": "ARE",
    "MID-AMERICA": "MAA", "MAA": "MAA",
    "UDR": "UDR", "ESS": "ESS", "ESSENTIAL": "ESS",
    "HOST HOTELS": "HST", "HST": "HST",
    "HEALTHPEAK": "PEAK", "PEAK": "PEAK",
    "KIMCO": "KIM", "KIMCO REALTY": "KIM",
    "REGENCY": "REG", "REGENCY CENTERS": "REG",
    "FEDERAL REALTY": "FRT", "FRT": "FRT",
    "BOSTON PROPERTIES": "BXP", "BXP": "BXP",
    "VORNADO": "VNO", "VNO": "VNO",
    "SL GREEN": "SLG", "SLG": "SLG",
    "CBRE": "CBRE", "CBRE GROUP": "CBRE",
    "IRON MOUNTAIN": "IRM", "IRM": "IRM",
    "WEYERHAEUSER": "WY", "WY": "WY",
    "SBA COMMUNICATIONS": "SBAC", "SBAC": "SBAC",
    "INVITATION HOMES": "INVH", "INVH": "INVH",
    "CAMDEN": "CPT", "CPT": "CPT",
    # 公用事业
    "NEXTERA": "NEE", "NEXTERA ENERGY": "NEE", "NEE": "NEE",
    "DUKE ENERGY": "DUK", "DUK": "DUK",
    "SOUTHERN": "SO", "SOUTHERN COMPANY": "SO", "SO": "SO",
    "DOMINION": "D", "DOMINION ENERGY": "D", "D": "D",
    "AMERICAN ELECTRIC": "AEP", "AEP": "AEP",
    "SEMPRA": "SRE", "SRE": "SRE",
    "EXELON": "EXC", "EXC": "EXC",
    "XCEL": "XEL", "XCEL ENERGY": "XEL",
    "CONSOLIDATED EDISON": "ED", "CON ED": "ED", "ED": "ED",
    "PUBLIC SERVICE ENTERPRISE": "PEG", "PSEG": "PEG", "PEG": "PEG",
    "WEC ENERGY": "WEC", "WEC": "WEC",
    "EVERGY": "EVRG", "EVRG": "EVRG",
    "AMERICAN WATER": "AWK", "AWK": "AWK",
    "DTE": "DTE", "DTE ENERGY": "DTE",
    "EDISON INTERNATIONAL": "EIX", "EIX": "EIX",
    "ENTERGY": "ETR", "ETR": "ETR",
    "FIRSTENERGY": "FE", "FE": "FE",
    "PPL": "PPL", "PPL CORP": "PPL",
    "AMEREN": "AEE", "AEE": "AEE",
    "CMS ENERGY": "CMS", "CMS": "CMS",
    "CENTERPOINT": "CNP", "CNP": "CNP",
    "ATO": "ATO", "ATMOS": "ATO",
    "NIAGARA MOHAWK": "NI", "NI": "NI",
    "ALLIANT": "LNT", "LNT": "LNT",
    "PNM": "PNW", "PNW": "PNW",
    "NRG": "NRG", "NRG ENERGY": "NRG",
    "CONSTELLATION ENERGY": "CEG", "CEG": "CEG",
}
